[project]
name = "zagruz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyqt6>=6.8.1",
    "yt-dlp>=2025.3.31",
]

[project.optional-dependencies]
package = [
    "pyinstaller>=6.0.0",
]

[tool.basedpyright]
reportImplicitStringConcatenation = false
