name: Release

on:
  workflow_run:
    workflows: ["Packages"]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Version ${{ github.ref_name }}"
          body: "Automated release for zagruz ${{ github.ref_name }}"
            dist/*.exe
            dist/*
            dist/*.whl
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
